<a href="https://colab.research.google.com/github/Srayoshi-Mirza/becoming-kung-fu-pandas/blob/main/Dinosaur_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("smruthiiii/dinosaur-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/smruthiiii/dinosaur-dataset/1.archive...

100%|██████████| 90.5k/90.5k [00:00<00:00, 37.5MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/smruthiiii/dinosaur-dataset/versions/1

In [3]:
df = pd.read_csv(path + "/dinosaurs.csv")

In [4]:
df.head(10)

,occurrence_no,name,diet,type,length_m,max_ma,min_ma,region,lng,lat,class,family
0,130294,Protarchaeopteryx,omnivorous,small theropod,2.0,130.0,122.46,Liaoning,120.733330,41.799999,Saurischia,Archaeopterygidae
1,130295,Caudipteryx,omnivorous,small theropod,1.0,130.0,122.46,Liaoning,120.733330,41.799999,Saurischia,Caudipterygidae
2,139242,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.528732,50.740726,Saurischia,Tyrannosauridae
3,139250,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.549347,50.737015,Saurischia,Tyrannosauridae
4,139252,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.564636,50.723866,Saurischia,Tyrannosauridae
5,139253,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.525337,50.740471,Saurischia,Tyrannosauridae
6,139254,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.601021,50.786999,Saurischia,Tyrannosauridae
7,139255,Albertosaurus,carnivorous,large theropod,9.0,72.1,66.00,Alberta,-112.981903,51.804600,Saurischia,Tyrannosauridae
8,139256,Albertosaurus,carnivorous,large theropod,9.0,70.6,66.00,Alberta,-112.981903,51.819099,Saurischia,Tyrannosauridae
9,139257,Albertosaurus,carnivorous,large theropod,9.0,83.5,70.60,Alberta,-112.818901,51.542702,Saurischia,Tyrannosauridae

In [5]:
df.head()

,occurrence_no,name,diet,type,length_m,max_ma,min_ma,region,lng,lat,class,family
0,130294,Protarchaeopteryx,omnivorous,small theropod,2.0,130.0,122.46,Liaoning,120.733330,41.799999,Saurischia,Archaeopterygidae
1,130295,Caudipteryx,omnivorous,small theropod,1.0,130.0,122.46,Liaoning,120.733330,41.799999,Saurischia,Caudipterygidae
2,139242,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.528732,50.740726,Saurischia,Tyrannosauridae
3,139250,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.549347,50.737015,Saurischia,Tyrannosauridae
4,139252,Gorgosaurus,carnivorous,large theropod,8.6,83.5,70.60,Alberta,-111.564636,50.723866,Saurischia,Tyrannosauridae

In [6]:
df.tail()

,occurrence_no,name,diet,type,length_m,max_ma,min_ma,region,lng,lat,class,family
4946,1360627,Isaberrysaura,NaN,NaN,NaN,171.6,168.4,Neuquén,-70.263290,-39.205288,Ornithischia,NaN
4947,1363632,Stegosaurus,herbivorous,armored dinosaur,9.0,157.3,152.1,Wyoming,-107.816666,44.650002,Ornithischia,Stegosauridae
4948,1363633,Othnielosaurus,NaN,NaN,NaN,157.3,152.1,Wyoming,-107.816666,44.650002,Ornithischia,NaN
4949,1364695,Iguanodon,herbivorous,ornithopod,10.0,145.0,139.8,Niedersachsen,9.959357,52.341167,Ornithischia,NaN
4950,1365108,Luluichnus,NaN,NaN,NaN,139.8,125.0,Western Australia,122.142029,-17.489502,Ornithischia,NaN

In [7]:
df.tail(10)

,occurrence_no,name,diet,type,length_m,max_ma,min_ma,region,lng,lat,class,family
4941,1350473,Edmontosaurus,herbivorous,ornithopod,13.0,72.1,66.0,Montana,-105.080002,45.660000,Ornithischia,Hadrosauridae
4942,1350474,Triceratops,herbivorous,ceratopsian,9.0,72.1,66.0,Montana,-105.078613,45.678333,Ornithischia,Ceratopsidae
4943,1350475,Pachycephalosaurus,herbivorous,ornithopod,8.0,72.1,66.0,Montana,-105.078613,45.678333,Ornithischia,Pachycephalosauridae
4944,1358692,Stegosaurus,herbivorous,armored dinosaur,9.0,157.3,145.0,Colorado,-108.728333,39.158890,Ornithischia,Stegosauridae
4945,1358696,Othnielosaurus,NaN,NaN,NaN,157.3,145.0,Colorado,-108.995796,39.238300,Ornithischia,NaN
4946,1360627,Isaberrysaura,NaN,NaN,NaN,171.6,168.4,Neuquén,-70.263290,-39.205288,Ornithischia,NaN
4947,1363632,Stegosaurus,herbivorous,armored dinosaur,9.0,157.3,152.1,Wyoming,-107.816666,44.650002,Ornithischia,Stegosauridae
4948,1363633,Othnielosaurus,NaN,NaN,NaN,157.3,152.1,Wyoming,-107.816666,44.650002,Ornithischia,NaN
4949,1364695,Iguanodon,herbivorous,ornithopod,10.0,145.0,139.8,Niedersachsen,9.959357,52.341167,Ornithischia,NaN
4950,1365108,Luluichnus,NaN,NaN,NaN,139.8,125.0,Western Australia,122.142029,-17.489502,Ornithischia,NaN

In [8]:
df.columns

Index(['occurrence_no', 'name', 'diet', 'type', 'length_m', 'max_ma', 'min_ma',
       'region', 'lng', 'lat', 'class', 'family'],
      dtype='object')

In [9]:
df.columns.tolist()

['occurrence_no',
 'name',
 'diet',
 'type',
 'length_m',
 'max_ma',
 'min_ma',
 'region',
 'lng',
 'lat',
 'class',
 'family']

In [10]:
df.dtypes

occurrence_no      int64
name              object
diet              object
type              object
length_m         float64
max_ma           float64
min_ma           float64
region            object
lng              float64
lat              float64
class             object
family            object
dtype: object

In [11]:
df.describe()

,occurrence_no,length_m,max_ma,min_ma,lng,lat
count,4.951000e+03,3568.000000,4951.000000,4951.000000,4951.000000,4951.000000
mean,6.838323e+05,8.212688,117.518477,106.622270,-37.048675,34.591448
std,3.021524e+05,6.629887,45.270821,44.395885,84.591106,23.961138
min,1.302090e+05,0.450000,70.600000,66.000000,-153.247498,-84.333336
25%,4.871225e+05,3.000000,83.500000,70.600000,-108.258705,36.274439
50%,5.618050e+05,6.700000,99.600000,89.800000,-96.099998,42.611198
75%,8.675665e+05,10.000000,155.700000,145.000000,27.383331,47.745138
max,1.365954e+06,35.000000,252.170000,247.200000,565.000000,78.101875

In [13]:
df.describe(include="all")

,occurrence_no,name,diet,type,length_m,max_ma,min_ma,region,lng,lat,class,family
count,4.951000e+03,4951,3596,3596,3568.000000,4951.000000,4951.000000,4909,4951.000000,4951.000000,4951,3494
unique,NaN,1042,3,6,NaN,NaN,NaN,287,NaN,NaN,2,75
top,NaN,Richardoestesia,herbivorous,ornithopod,NaN,NaN,NaN,Alberta,NaN,NaN,Saurischia,Dromaeosauridae
freq,NaN,151,2076,811,NaN,NaN,NaN,650,NaN,NaN,3074,450
mean,6.838323e+05,NaN,NaN,NaN,8.212688,117.518477,106.622270,NaN,-37.048675,34.591448,NaN,NaN
std,3.021524e+05,NaN,NaN,NaN,6.629887,45.270821,44.395885,NaN,84.591106,23.961138,NaN,NaN
min,1.302090e+05,NaN,NaN,NaN,0.450000,70.600000,66.000000,NaN,-153.247498,-84.333336,NaN,NaN
25%,4.871225e+05,NaN,NaN,NaN,3.000000,83.500000,70.600000,NaN,-108.258705,36.274439,NaN,NaN
50%,5.618050e+05,NaN,NaN,NaN,6.700000,99.600000,89.800000,NaN,-96.099998,42.611198,NaN,NaN
75%,8.675665e+05,NaN,NaN,NaN,10.000000,155.700000,145.000000,NaN,27.383331,47.745138,NaN,NaN
max,1.365954e+06,NaN,NaN,NaN,35.000000,252.170000,247.200000,NaN,565.000000,78.101875,NaN,NaN

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4951 entries, 0 to 4950
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   occurrence_no  4951 non-null   int64
 1   name           4951 non-null   object
 2   diet           3596 non-null   object
 3   type           3596 non-null   object
 4   length_m       3568 non-null   float64
 5   max_ma         4951 non-null   float64
 6   min_ma         4951 non-null   float64
 7   region         4909 non-null   object
 8   lng            4951 non-null   float64
 9   lat            4951 non-null   float64
 10  class          4951 non-null   object
 11  family         3494 non-null   object
dtypes: float64(5), int64(1), object(6)
memory usage: 464.3+ KB